// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_D5m-dt_hf1mvi4CvGc7iJ6DVTRnmVw',
    appId: '1:217207124016:web:3cd7abc0233742ee443df5',
    messagingSenderId: '217207124016',
    projectId: 'course-udemy-bloc',
    authDomain: 'course-udemy-bloc.firebaseapp.com',
    storageBucket: 'course-udemy-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMHGMy6zP0GKL7qCO-ODw4AtJ9NdsKx2I',
    appId: '1:217207124016:android:9273ab97dea65bb5443df5',
    messagingSenderId: '217207124016',
    projectId: 'course-udemy-bloc',
    storageBucket: 'course-udemy-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANAR6MMlKDLm2PNcPnz5-fo6KYMV4hjMw',
    appId: '1:217207124016:ios:5e5f6035073ed89a443df5',
    messagingSenderId: '217207124016',
    projectId: 'course-udemy-bloc',
    storageBucket: 'course-udemy-bloc.appspot.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANAR6MMlKDLm2PNcPnz5-fo6KYMV4hjMw',
    appId: '1:217207124016:ios:5e5f6035073ed89a443df5',
    messagingSenderId: '217207124016',
    projectId: 'course-udemy-bloc',
    storageBucket: 'course-udemy-bloc.appspot.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL_D5m-dt_hf1mvi4CvGc7iJ6DVTRnmVw',
    appId: '1:217207124016:web:224ab1655cc50176443df5',
    messagingSenderId: '217207124016',
    projectId: 'course-udemy-bloc',
    authDomain: 'course-udemy-bloc.firebaseapp.com',
    storageBucket: 'course-udemy-bloc.appspot.com',
  );
}
